package com.nextcontrols.domain;
// default package
// Generated 09-Feb-2010 15:54:24 by Hibernate Tools 3.2.2.GA


import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;



/**
 * KeyholderList generated by hbm2java
 */
public class KeyholderList implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int keyholderListId;
	private String listName;
	private String listType;
	private Date startDate;
	private Date endDate;
	private String occupancyStart;
	private String occupancyEnd;
	private String comments;
	private String commentsShort;
	private String weekdaysActive;	
	private boolean monday;
	private boolean tuesday;
	private boolean wednesday;
	private boolean thursday;
	private boolean friday;
	private List<Keyholder> keyholders;
	private String displayName;
	private String description;
	
	
	public KeyholderList() {
		monday=false;
		tuesday=false;
		wednesday=false;
		thursday=false;
		friday=false;
		keyholders = new ArrayList <Keyholder>();
	}

	public KeyholderList(int keyholderListId,String listName ,String listType, Timestamp startTime,Timestamp endTime,String occupancyStart,
			String occupancyEnd,String comments,String weekdaysActive) {
		monday=false;
		tuesday=false;
		wednesday=false;
		thursday=false;
		friday=false;
		keyholders = new ArrayList <Keyholder>();
		this.listName=listName;
		this.keyholderListId = keyholderListId;
		this.listType = listType;
		this.startDate = startTime;
		this.endDate = endTime;
		this.occupancyStart=occupancyStart;
		this.occupancyEnd=occupancyEnd;
		this.comments=comments;
		this.commentsShort=comments;
		this.weekdaysActive=weekdaysActive;
		convertWeekdaysActive();
	}
	
	public int getKeyholderListId() {
		return keyholderListId;
	}

	public void setKeyholderListId(int keyholderListId) {
		this.keyholderListId = keyholderListId;
	}

	public String getListName() {
		return listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	public String getListType() {
		return listType;
	}

	public void setListType(String listType) {
		this.listType = listType;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startTime) {
		this.startDate = startTime;
		
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endTime) {
		endDate = endTime;
	}

	public List<Keyholder> getKeyholders() {
		return keyholders;
	}

	public void setKeyholders(List<Keyholder> keyholders) {
		this.keyholders = keyholders;
	}

	public void addKeyholders(Keyholder keyholder){
		this.keyholders.add(keyholder);
	}
	
	public void setOccupancyStart(String occupancyStart) {
		this.occupancyStart = occupancyStart;
	}

	public String getOccupancyStart() {
		return occupancyStart;
	}

	public void setOccupancyEnd(String occupancyEnd) {
		this.occupancyEnd = occupancyEnd;
	}

	public String getOccupancyEnd() {
		return occupancyEnd;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getComments() {
		return comments;
	}

	public void setCommentsShort(String commentsShort) {
		if (commentsShort==null){
			this.commentsShort = "";
		}else{
			if (commentsShort.length()>29){
				this.commentsShort =new String(commentsShort.substring(0, 29));
			}else{
				this.commentsShort =commentsShort;
			}
		}
	}

	public String getCommentsShort() {
		return commentsShort;
	}

	public void setMonday(boolean monday) {
		this.monday = monday;
		changeWeekdaysActive(1, this.monday);
	}

	public boolean isMonday() {
		return monday;
	}

	public void setTuesday(boolean tuesday) {
		this.tuesday = tuesday;
		changeWeekdaysActive(2, this.tuesday);
	}

	public boolean isTuesday() {
		return tuesday;
	}

	public void setWednesday(boolean wednesday) {
		this.wednesday = wednesday;
		changeWeekdaysActive(3, this.wednesday);
	}

	public boolean isWednesday() {
		return wednesday;
	}

	public void setThursday(boolean thursday) {
		this.thursday = thursday;
		changeWeekdaysActive(4, this.thursday);
	}

	public boolean isThursday() {
		return thursday;
	}

	public void setFriday(boolean friday) {
		this.friday = friday;
		changeWeekdaysActive(5, this.friday);
	}

	public boolean isFriday() {
		return friday;
	}

	public void setWeekdaysActive(String weekdaysActive) {
		this.weekdaysActive = weekdaysActive;
		if (weekdaysActive!=null){
			convertWeekdaysActive();
		}
	}

	public String getWeekdaysActive() {
		return weekdaysActive;
	}
	
	public void convertWeekdaysActive(){
		if (this.weekdaysActive!=null){
			String[] weekday=this.weekdaysActive.split(",");
			for (int i=0;i<=weekday.length-1;i++){
				int dayNumb=Integer.parseInt(weekday[i]);
				switch (dayNumb){
				case 1:
					this.monday=true;
					break;
				case 2:
					this.tuesday=true;
					break;
				case 3:
					this.wednesday=true;
					break;
				case 4:
					this.thursday=true;
					break;
				case 5:
					this.friday=true;
					break;
				default:
					break;
				}
			}
		}
	}
	
	public void changeWeekdaysActive(int day, boolean add){
		if (add==true){
			if (this.weekdaysActive!=null){
				String dayStr=String.valueOf(day);
				if (this.weekdaysActive.indexOf(dayStr)==-1){
					this.weekdaysActive+=day + ",";
				}
			}else{
				this.weekdaysActive=day + ",";
			}
		}else{
			if (this.weekdaysActive!=null){
				char dayString=Character.forDigit(day, 10);
				String newRange="";
				for (int i=0;i<=this.weekdaysActive.length()-1;i++){
					if (dayString!=this.weekdaysActive.charAt(i)){
						newRange+=this.weekdaysActive.charAt(i);
					}else if(dayString==this.weekdaysActive.charAt(i)){
						if (i<this.weekdaysActive.length()-1){
							if (this.weekdaysActive.charAt(i+1)==','){
								i+=1;
							}
						}
					}
				}
				this.weekdaysActive=newRange;
			}
		}
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
