package com.nextcontrols.domain;
// default package
// Generated 09-Feb-2010 15:54:24 by Hibernate Tools 3.2.2.GA

/**
 * KeyholderListKeyholdersId generated by hbm2java
 */
public class KeyholderListKeyholdersId implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Keyholder keyholder;
	private KeyholderList keyholderList;

	public KeyholderListKeyholdersId() {
	}

	public KeyholderListKeyholdersId(Keyholder keyholder,
			KeyholderList keyholderList) {
		this.keyholder = keyholder;
		this.keyholderList = keyholderList;
	}

	public Keyholder getKeyholder() {
		return this.keyholder;
	}

	public void setKeyholder(Keyholder keyholder) {
		this.keyholder = keyholder;
	}

	public KeyholderList getKeyholderList() {
		return this.keyholderList;
	}

	public void setKeyholderList(KeyholderList keyholderList) {
		this.keyholderList = keyholderList;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KeyholderListKeyholdersId))
			return false;
		KeyholderListKeyholdersId castOther = (KeyholderListKeyholdersId) other;

		return ((this.getKeyholder() == castOther.getKeyholder()) || (this
				.getKeyholder() != null
				&& castOther.getKeyholder() != null && this.getKeyholder()
				.equals(castOther.getKeyholder())))
				&& ((this.getKeyholderList() == castOther.getKeyholderList()) || (this
						.getKeyholderList() != null
						&& castOther.getKeyholderList() != null && this
						.getKeyholderList()
						.equals(castOther.getKeyholderList())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKeyholder() == null ? 0 : this.getKeyholder().hashCode());
		result = 37
				* result
				+ (getKeyholderList() == null ? 0 : this.getKeyholderList()
						.hashCode());
		return result;
	}

}
