package com.nextcontrols.domain;
// default package
// Generated 09-Feb-2010 15:54:24 by Hibernate Tools 3.2.2.GA

/**
 * KeyholderListKeyholders generated by hbm2java
 */
public class KeyholderListKeyholders implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private KeyholderListKeyholdersId id;
	private int listPriority;
	private Boolean active;

	public KeyholderListKeyholders() {
	}

	public KeyholderListKeyholders(KeyholderListKeyholdersId id,
			int listPriority) {
		this.id = id;
		this.listPriority = listPriority;
	}

	public KeyholderListKeyholders(KeyholderListKeyholdersId id,
			int listPriority, Boolean active) {
		this.id = id;
		this.listPriority = listPriority;
		this.active = active;
	}

	public KeyholderListKeyholdersId getId() {
		return this.id;
	}

	public void setId(KeyholderListKeyholdersId id) {
		this.id = id;
	}

	public int getListPriority() {
		return this.listPriority;
	}

	public void setListPriority(int listPriority) {
		this.listPriority = listPriority;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
